version: '3.8'
services: 
    node:
        build:
            context: ./app/
        env_file: ./app/.env
        command: npm start
        restart: always
        volumes: 
            - .:/app/
            - /app/node_modules
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        depends_on: 
            - mysqldb
        environment: 
            MYSQL_HOST: mysqldb

    mysqldb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file: ./app/.env
        environment: 
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        volumes:
            - ./app/gps_data.sql:/docker-entrypoint-initdb.d/init.sql:rw

    rabbitmq:
        image: rabbitmq:management-alpine
        restart: always
        env_file: ./app/.env
        ports:
            - $RABBIT_LOCAL_PORT:$RABBIT_DOCKER_PORT
            - $RABBIT_LOCAL_MANAGEMENT_PORT:$RABBIT_DOCKER_MANAGEMENT_PORT
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
